version: '3.9'

services:
  mysql:
    image: mysql:8.1
    container_name: microservice_purchasing_db 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: microservice_purchasing
    volumes:
      - mysql_data:/var/lib/mysql

  microservice_purchasing:
    build:
      context: ./ 
    image: microservice_purchasing:latest
    container_name: microservice_purchasing
    ports:
      - "8089:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/microservice_purchasing
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - mysql
    restart: always
    command: ["java", "-jar", "app.jar"]

volumes:
  mysql_data: